export const ONBOARDING_COMPLETE = 'ONBOARDING_COMPLETE'
export const ONBOARDING_VALIDATE = 'ONBOARDING_VALIDATE'
export const ONBOARDING_STORE = 'ONBOARDING_STORE'
export const ONBOARDING_FAIL = 'ONBOARDING_FAIL'
