export const ONBOARDING_COMPLETE = 'ONBOARDING_COMPLETE'
export const ONBOARDING_VALIDATE = 'ONBOARDING_VALIDATE'
export const ONBOARDING_STORE = 'ONBOARDING_STORE'
export const ONBOARDING_FAIL = 'ONBOARDING_FAIL'


export const REPORTER_MAP_REGION_CHANGED = 'REPORTER_MAP_REGION_CHANGED'
export const REPORTER_REPORT_CREATED = 'REPORTER_REPORT_CREATED'

export const REPORT_STORE = 'REPORT_STORE'
export const REPORT_MESSAGE_RECEIVED = 'REPORT_MESSAGE_RECEIVED'
export const RESPONDER_PARTNER_CHOSEN = 'RESPONDER_PARTNER_CHOSEN'
