#!/bin/bash
mkdir -p android/app/src/main/assets
ENVFILE=`eval 'echo ".env.$NODE_ENV"'`
npx react-native bundle --platform android --dev false --entry-file index.android.js   --bundle-output android/app/src/main/assets/index.android.bundle  --assets-dest android/app/src/main/res/
